[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_swap_nft = "A9y6CZyMtprMecUJnjWC9fhcfrXGPGK9wwK4qxoEEj6Q"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
